# Generated by Django 5.1.6 on 2026-05-05 11:22

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_project_userimage_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=webapp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
