# Generated by Django 5.1.6 on 2026-05-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_userimage_options_remove_userimage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cover',
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.project')),
            ],
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
