# Generated by Django 5.1.6 on 2026-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_project_cover_projectphoto_delete_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='კატეგორიის სახელი')),
                ('slug', models.SlugField(unique=True, verbose_name='URL იდენტიფიკატორი')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='projects', to='webapp.category'),
        ),
    ]
