# Generated by Django 5.1.6 on 2026-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_category_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
    ]
