# Generated by Django 5.1.6 on 2026-05-31 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_profile_profession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
