# Generated by Django 5.1.6 on 2026-05-31 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_project_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
